// packages/vue-client-ts/src/components/core/trades/Settings.vue
<!--<template>-->
<!--  <div class="drawer">-->
<!--    <div class="drawer-title">-->
<!--      <div class="drawer-title-text">Widget settings</div>-->
<!--      <CloseIcon onClick={this.drawerClose.bind(this, this.props.data.drawer)} className="pointer" />-->
<!--    </div>-->
<!--    <PerfectScrollbar option={{'suppressScrollX': true}} :style="['height': 'calc(100vh - 49px)']">-->
<!--    <CommonSettings data={this.props.data}/>-->
<!--      <Divider />-->
<!--      </PerfectScrollbar>-->
<!--  </div>-->
<!--</template>-->

<!--<script lang="ts">-->
<!--import { Component, Vue } from 'vue-property-decorator'-->

<!--@Component({-->
<!--  name: 'Settings'-->
<!--})-->
<!--export default class Settings extends Vue {-->
<!--  drawerClose (drawer: any) {-->
<!--    DrawersStore.drawerClose(drawer)-->
<!--  }-->
<!--}-->
<!--</script>-->

<!--<style scoped>-->

<!--</style>-->

// packages/react-client/src/core_components/Selector/Settings.js
import React from 'react'
import { observer } from 'mobx-react'
import Divider from '@material-ui/core/Divider'
import _ from 'lodash'
import CloseIcon from '@material-ui/icons/Close'
import PerfectScrollbar from 'react-perfect-scrollbar'
import CommonSettings from 'core_components/Settings/Common.js'

import DrawersStore from 'stores/DrawersStore'

@observer
class Settings extends React.Component {
  render() {
    return (
      <div className="drawer">
        <div className="drawer-title">
          <div className="drawer-title-text">Widget settings</div>
          <CloseIcon onClick={this.drawerClose.bind(this, this.props.data.drawer)} className="pointer" />
        </div>
        <Divider />
        <PerfectScrollbar option={{'suppressScrollX': true}} style={{height: 'calc(100vh - 49px)'}}>
          <CommonSettings data={this.props.data}/>
          <Divider />
        </PerfectScrollbar>
      </div>
    )
  }
  drawerClose(drawer) {
    DrawersStore.drawerClose(drawer)
  }
}

export default Settings
