// vue-client/src/core_components/Stocks/Stocks.vue
<template>
  <div class="kupi-table">
    <table>
      <tbody>
        <tr v-for="item in dataComputed" :key="item.uuid">
          <td>{{item['stock']}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
import moment from 'moment'
import _ from 'lodash'
export default {
  data() {
    return {
      data: require('./data.js').default
    }
  },
  created() {
  },
  methods: {
  },
  computed: {
    dataComputed: function() {
      var data = _.cloneDeep(this.data)
      return _.map(data, (item)=>{
        return {
          uuid: item.uuid,
          stock: item.name
        }
      })

    }
  }
}
</script>

<style lang="sass"></style>

// react-client/src/core_components/Stocks.js
import React from 'react'
import _ from 'lodash'
import { inject, observer } from 'mobx-react'

@inject('GlobalStore')
@observer
class Stocks extends React.Component {
  render() {
    const {GlobalStore, type} = this.props
    return (
      <div>
        <table>
          <tbody>
            {
              _.map(GlobalStore.stocks, (stock) => {
                return <tr key={stock}>
                  <td><a href="#" onClick={this.handleClick.bind(this, stock.name)}>{stock.name}</a></td>
                </tr>
              })
            }
          </tbody>
        </table>
      </div>
    )
  }
  handleClick(stock) {
    this.props.GlobalStore.setStock(stock)
  }
}

export default Stocks
