// react-client/src/core_components/MyTrades.js
import React from 'react'
import _ from 'lodash'
import { observer } from 'mobx-react'
import moment from 'moment'
import MyTradesStore from '../stores/MyTradesStore'

@observer
class MyTrades extends React.Component {
  render() {
    return (
      <div>
        <table className="simpleTable">
          <thead>
            <tr>
              <th>id</th>
              <th>date</th>
              <th>symbol</th>
              <th>type</th>
              <th>side</th>
              <th>price</th>
              <th>amount</th>
              <th>cost</th>
              <th>fee</th>
            </tr>
          </thead>
          <tbody>
          {
            _.map(MyTradesStore.myTrades, (item) => {
              return (
                <tr key={item.uuid}>
                  <td>{item['order']}</td>
                  <td>{moment(item['datetime']).format('DD.MM.YY HH:mm:ss')}</td>
                  <td>{item['symbol']}</td>
                  <td>{item['type']}</td>
                  <td>{item['side']}</td>
                  <td>{item['price'].toFixed(8)}</td>
                  <td>{item['amount']}</td>
                  <td>{item['cost']}</td>
                  <td>{item['fee']['cost'].toFixed(8)} {item['fee']['currency']}</td>
                </tr>
              )
            })
          }
          </tbody>
        </table>
      </div>
    )
  }
  componentDidMount() {
    MyTradesStore.count(1)
  }
  componentWillUnmount() {
    MyTradesStore.count(-1)
  }
}

export default MyTrades

// vue-client/src/core_components/MyTrades/MyTrades.vue
<template>
  <div class="kupi-table">
    <table>
      <thead>
        <tr>
          <th>id</th>
          <th>date</th>
          <th>symbol</th>
          <th>type</th>
          <th>side</th>
          <th>price</th>
          <th>amount</th>
          <th>cost</th>
          <th>fee</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item in dataComputed" :key="item.uuid">
          <td>{{item['order']}}</td>
          <td>{{item['datetime']}}</td>
          <td>{{item['symbol']}}</td>
          <td>{{item['type']}}</td>
          <td>{{item['side']}}</td>
          <td>{{item['price']}}</td>
          <td>{{item['amount']}}</td>
          <td>{{item['cost']}}</td>
          <td>{{item['fee']}}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
  import axios from 'axios'
  import moment from 'moment'
  import _ from 'lodash'
  export default {
  data() {
    return {
      data: require('./data.js').default
    }
  },
  created() {
  },
  mounted: function() {
    var accountId = 'ID_Binance_2'
    var pair = 'ETH_BTC'
    axios.get(`/user-api/myTrades/${accountId}/${pair}`)
    .then((response) => {
      this.data = response.data
    })
    .catch((error) => {
      this.error = error
    })
  },
  methods: {
  },
  computed: {
    dataComputed: function() {
      var data = _.cloneDeep(this.data)
      // console.log(data)
      return _.map(data, (item)=>{
        return {
          uuid: item.uuid,
          order: item.order,
          datetime: moment(item).format('DD.MM.YY HH:mm:ss'),
          symbol: item.symbol,
          type: item.type,
          side: item.side,
          price: item.price.toFixed(8),
          amount: item.amount,
          cost: item.cost,
          fee: item['fee']['cost'].toFixed(8) + ' ' + item['fee']['currency']
        }
      })

    }
  }
}
</script>

<style lang="sass"></style>
