// packages/vue-client-ts/src/components/core/trades/Settings.vue
<!--<template>-->
<!--  <div class="drawer">-->
<!--    <div class="drawer-title">-->
<!--      <div class="drawer-title-text">Widget settings</div>-->
<!--      <CloseIcon onClick={this.drawerClose.bind(this, this.props.data.drawer)} className="pointer" />-->
<!--    </div>-->
<!--    <PerfectScrollbar option={{'suppressScrollX': true}} :style="['height': 'calc(100vh - 49px)']">-->
<!--    <CommonSettings data={this.props.data}/>-->
<!--      <Divider />-->
<!--      </PerfectScrollbar>-->
<!--  </div>-->
<!--</template>-->

<!--<script lang="ts">-->
<!--import { Component, Vue } from 'vue-property-decorator'-->

<!--@Component({-->
<!--  name: 'Settings'-->
<!--})-->
<!--export default class Settings extends Vue {-->
<!--  drawerClose (drawer: any) {-->
<!--    DrawersStore.drawerClose(drawer)-->
<!--  }-->
<!--}-->
<!--</script>-->

<!--<style scoped>-->

<!--</style>-->

// react-client/src/core_components/Iframe/Settings.js
import React from 'react'
import { observer } from 'mobx-react'
import TextField from '@material-ui/core/TextField'
import Divider from '@material-ui/core/Divider'
import _ from 'lodash'
import CloseIcon from '@material-ui/icons/Close'
import PerfectScrollbar from 'react-perfect-scrollbar'

import DashboardsStore from 'stores/DashboardsStore'
import DrawersStore from 'stores/DrawersStore'

@observer
class Settings extends React.Component {
  render() {
    var {dashboardId, widgetId} = this.props.data
    var widget = _.find(DashboardsStore.dashboards[dashboardId].widgets, ['i', widgetId])
    var customHeader = widget.customHeader
    var {url} = widget.data
    return (
      <div className="drawer">
        <div className="drawer-title">
          <div className="drawer-title-text">Widget settings</div>
          <CloseIcon onClick={this.drawerClose.bind(this, this.props.data.drawer)} className="pointer" />
        </div>
        <Divider />
        <PerfectScrollbar option={{'suppressScrollX': true}} style={{height: 'calc(100vh - 49px)'}}>
          <form className='section-body' noValidate autoComplete="off">
            <TextField
              id="outlined-name"
              label="Name"
              value={customHeader}
              onChange={this.changeCustomHeader.bind(this)}
              variant="outlined"
              fullWidth
              className="mb-16"
            />
            <TextField
              id="outlined-name"
              label="Url"
              value={url}
              onChange={this.setWidgetData.bind(this, 'url', 'value')}
              variant="outlined"
              fullWidth
            />
          </form>
          <Divider />
        </PerfectScrollbar>
      </div>
    )
  }
  changeCustomHeader(e) {
    var {dashboardId, widgetId} = this.props.data
    var value = e.target.value.trim()
    DashboardsStore.setCustomHeader(dashboardId, widgetId, value)
  }
  setWidgetData(key, attr, e) {
    var {dashboardId, widgetId} = this.props.data
    var value = e.target[attr]
    DashboardsStore.setWidgetData(dashboardId, widgetId, key, value)
  }
  drawerClose(drawer) {
    DrawersStore.drawerClose(drawer)
  }
}

export default Settings
